### PR TITLE
override LINUX_VERSION_CODE is merged, delete extra patches

### PR DESCRIPTION
**Pull request by iotcg**
bcc commit bfecc24 has been merged. There's no need to maintain
seperate patches

Signed-off-by: Liu Changcheng <changcheng.liu@aliyun.com>

### CODE REVIEW

**Comment by joelagnel** [comment]
The deletion of patches has to accompanied by a change to bashrc too.
Upstream uses `BCC_LINUX_VERSION_CODE`.

Also I will have to update prebuilt BCC in the releases or the changes will break the release. I'll clean this up this week.

**Comment by joelagnel** [comment]
Agreed on the china mirror patch. I will merge just that patch for now while we're discussing the other changes.

**Comment by iotcg** [comment]
"WA link issue" means "workaround link issue".
I enabled your code base on x86 Android platform. There're some "ldd link issues", such as "/usr/bin/ld: cannot find -lstdc++". The reason is that ldd can't find the right library. I have to manually set LIBRARY_PATH environment variable to tell ldd where to find the required library.

**Comment by joelagnel** [comment]
I generally don't like WA (workarounds) unless there's other options:

About this patch:
```
x86 kernel header: set CPATH env for x86 device, I stl
```

Currently for building BCC on x86, there is no need for specifying CPATH. The x86 instructions are here: 
https://github.com/iovisor/bcc/blob/master/INSTALL.md

There could be some limitation in adeb filesystem, but since arm64 bcc builds work, I doubt that. I will try an x86 target soon and let you know. Thanks!

**Comment by joelagnel** [comment]
So I fixed 1/5 and merged 5/5. For 3/5 4/5 and 5/5, I want to spend more time fixing it properly.

**Pull request closed without merging**
