### PR TITLE
utils: add kbuildout support for out-of-tree kernel builds

### PR DESCRIPTION
**Pull request by duyuchao**
Signed-off-by: yuchao.du@unisoc.com

### CODE REVIEW

**Comment by joelagnel** [comment]
Hi, I will hold off to merging this since we are moving towards providing the headers within the kernel: https://lore.kernel.org/patchwork/patch/1067310/ . Soon, this will be the way to go.

**Comment by duyuchao** [comment]
ok, i see

**Comment by joelagnel** [comment]
Could you experiment with that? I wanted to actually delete all the code in
adeb that has to be with kernel headers, simply because the kernel
mechanism I shared with you eliminates the need for that code. It even
works for out-of-tree builds. Appreciate any help on this

**Comment by duyuchao** [comment]
sure, my pleasure, i will try after chinese holiday

**Comment by duyuchao** [comment]
hi  joelagnel,
I try the https://lore.kernel.org/patchwork/patch/1067310/, and it works well on my side.

**Comment by joelagnel** [comment]
Thanks for confirming.

**Pull request closed without merging**
